version: "3"
services:
  app:
    container_name: "my-node-api"
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ".:/usr/src/app"
    ports:
      - "9001:3000"
    depends_on:
      - db
  db:
    container_name: "my-mongo-db"
    image: "mongo"
    restart: "always"
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"